### ISSUE TITLE
Not able to Download the pre-trained model.

### ISSUE THREAD

**Issue by DecentMakeover** [Vipermdl/OCR_detection_IC15#4]
Hi

Thanks for sharing your work and also uploading the model.But , i am not able to download the model from baidu.Could you maybe upload it on google drive too or dropbox.

Thanks in advance

**Comment by WrathofBhuvan11** [comment]
I actually downloaded it from baidu
link "retrained_model.tar"- 298MB
extracting this gives error

**Comment by ZhangWen0301** [comment]
@WrathofBhuvan11 no need to extract the "retrained_model.pth.tar" file, the model file is working.

**Comment by novioleo** [comment]
@DecentMakeover 
https://drive.google.com/file/d/1oYfxKUA7YKZCnSgTN3Gk-u0N7uBPbJbT/view?usp=sharing

**Comment by mehrazi** [comment]
@DecentMakeover what was the training dataset?

**Comment by DecentMakeover** [comment]
@novioleo Thanks  for uploading
@mehrdadazizi72  what do you mean?

**Comment by mehrazi** [comment]
@DecentMakeover sorry, that was my mistake, I wanted to mention @novioleo.
@novioleo what was the training dataset for the pre-trained model.

**Comment by novioleo** [comment]
icdar2015


 
---Original---
